### ISSUE TITLE
panic: "index out of range" in //check 1bit FLAG of x,y coordinator 

### ISSUE THREAD

**Issue by kei969777** [orcastor/fico#2]
add an index check!

// check 1bit FLAG of x,y coordinator
func f(d []byte, x, y, w, h int) byte {
	index := (w >> 3 * ((h - 1) - y)) + (x >> 3)

	if index < 0 || index >= len(d) {
		return 0
	}

	//panic: index out of range
	return d[index] >> uint(0x07-(x&0x07)) & 1
}

ps. err in path := `C:\Users\xxxxx\AppData\Local\Programs\Another Redis Desktop Manager\Another Redis Desktop Manager.exe`

patch: https://github.com/orcastor/fico/commit/177df5b74d48fff031faac15e1140232a5e2ab59

**Comment by orca-zhang** [comment]
What are the arguments / statements you tried to extract icon from `Another Redis Desktop Manager.exe`?
I wanna reproduce the panic.
