### ISSUE TITLE
panic: runtime error: slice bounds out of range [:34032] with capacity 8704

### ISSUE THREAD

**Issue by ZeronoFreya** [orcastor/fico#3]
```
goroutine 1 [running]:
github.com/orcastor/fico.parseDir({0xc00013e000, 0x2200, 0x2200}, 0x3a0, {0xc00000a3a0, 0x4}, 0x55000)
        C:/Users/.../go/pkg/mod/github.com/orcastor/fico@v0.0.0-20240510133718-2bc39e68d222/fico.go:497 +0x765
github.com/orcastor/fico.parseDir({0xc00013e000, 0x2200, 0x2200}, 0xf0, {0xc00000a39a, 0x2}, 0x55000)
        C:/Users/.../go/pkg/mod/github.com/orcastor/fico@v0.0.0-20240510133718-2bc39e68d222/fico.go:483 +0x65e
github.com/orcastor/fico.parseDir({0xc00013e000, 0x2200, 0x2200}, 0x0, {0x0, 0x0}, 0x55000)
        C:/Users/.../go/pkg/mod/github.com/orcastor/fico@v0.0.0-20240510133718-2bc39e68d222/fico.go:483 +0x65e
github.com/orcastor/fico.PE2ICO({0xd48938, 0xc000062080}, {0xd134ab?, 0xe597c0?}, {0xc000107f08, 0x1, 0x1})
        C:/Users/.../go/pkg/mod/github.com/orcastor/fico@v0.0.0-20240510133718-2bc39e68d222/fico.go:600 +0x14f
github.com/orcastor/fico.F2ICO({0xd48938, 0xc000062080}, {0xd134ab, 0x1b}, {0xc000107f08, 0x1, 0x1})
        C:/Users/.../go/pkg/mod/github.com/orcastor/fico@v0.0.0-20240510133718-2bc39e68d222/fico.go:46 +0x125
main.main()
        E:/Project/Golang/Demo/exe_icon/main.go:39 +0x18b
```
可能这个程序特殊？
[Ruler.zip](https://github.com/user-attachments/files/16130281/Ruler.zip)

**Comment by orca-zhang** [comment]
parseDir这个方法是抄来的，我已经对它做了部分调整，可能存在不兼容的情况，我晚间抽空看一下

**Comment by orca-zhang** [comment]
看起来可能和ASPack加壳有关系，我用eXescope、Resource Hacker、PE Explorer打开这个exe，都读取不到正确的图标资源，但是Explorer能正常显示图标，很奇怪，目前暂时只修复了panic问题。

**Comment by orca-zhang** [comment]
验证了，从 http://old-dos.ru/index.php?page=files&mode=files&do=show&id=8296 下载了unaspack去掉壳以后就能正常获取图标了，我再研究一下，可能是reloc了。

下面是去掉壳的exe和获取的图标
[Ruler_new.zip](https://github.com/user-attachments/files/16166904/Ruler_new.zip)
![fico_demo](https://github.com/orcastor/fico/assets/13848506/d76087f8-af61-4095-aded-cf901ecf9686)

**Comment by orca-zhang** [comment]
你的建议很不错，我考虑新开一个Golang的脱壳项目，并且fico使用脱壳项目尝试更多可能。

**Comment by ZeronoFreya** [comment]
我发现了一个开源的程序: https://github.com/bertjohnson/ExtractIcon。源码看着挺简洁，能成功提取上面的rule程序。看着不像有去壳的过程，不过我也不懂c，可能漏看了

**Comment by orca-zhang** [comment]
这个直接用的Windows API，确实是可以实现的，操作系统也不会知道去壳的事情
但是fico是基于binary本身的数据实现的，所以要模拟运行时

**Comment by ZeronoFreya** [comment]
我倒是觉得与其脱壳，能用api的话更好，脱壳这一步骤是否有性能问题？是否会失败？不过，这些只是个人拙见，感觉获取图标还要脱壳有点反直觉

**Comment by orca-zhang** [comment]
api只能在windows使用，确认只在windows上的话，直接用ExtractIcon、ExtractIconEx的windows api就好了呃，fico要做的是在linux、macosx、android等平台无关可移植场景下，只通过静态二进制数据解析出图标，加壳的人只考虑了windows平台的兼容性，在explorer渲染时已经在运行时了
