### ISSUE TITLE
386 system build error

### ISSUE THREAD

**Issue by MACDVPN** [orcastor/fico#5]
set GOARCH=386
go build
github.com/orcastor/fico
github.com\orcastor\fico@v0.0.0-20240711053440-24cd61a770af\fico.go:470:11: 0x80000000 (untyped int constant 2147483648) overflows int
github.com\orcastor\fico@v0.0.0-20240711053440-24cd61a770af\fico.go:480:19: 0x80000000 (untyped int constant 2147483648) overflows int
![圖片](https://github.com/user-attachments/assets/8b598427-b626-40a3-ba77-037f04dc6cd8)

**Comment by orca-zhang** [comment]
I've got it. I'll use another way to implement this routine.

**Comment by orca-zhang** [comment]
You can try the latest version.

**Comment by MACDVPN** [comment]
Thank you, the test is normal now👌
